
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_DEPARTMENT')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_DEPARTMENT
GO

 CREATE PROCEDURE sp_insert_DEPARTMENT

@p_NAME varchar(250)  
AS
BEGIN
	Insert into DEPARTMENT ([NAME])
	values(@p_NAME)

END
GO





IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_update_DEPARTMENT')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_update_DEPARTMENT
GO

 CREATE PROCEDURE sp_update_DEPARTMENT
@p_NAME varchar(250) ,
@w_ID int,
@w_NAME varchar(250) 
AS
BEGIN
	UPDATE [dbo].DEPARTMENT SET [NAME]=@p_NAME 
	WHERE ID=@w_ID AND NAME=@w_NAME
END 
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_ROLE')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_ROLE
GO

 CREATE PROCEDURE sp_insert_ROLE

@p_NAME varchar(250)  
AS
BEGIN
	Insert into [ROLE] ([NAME])
	values(@p_NAME)
END 
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_update_ROLE')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_update_ROLE
GO

 CREATE PROCEDURE sp_update_ROLE
@p_NAME varchar(250) ,
@w_ID int,
@w_NAME varchar(250) 
AS
BEGIN
	UPDATE [dbo].[ROLE] SET [NAME]=@p_NAME 
	WHERE ID=@w_ID AND NAME=@w_NAME
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_STATUS_COMPLAIN')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_STATUS_COMPLAIN
GO

 CREATE PROCEDURE sp_insert_STATUS_COMPLAIN
@p_NAME varchar(250)  
AS
BEGIN
	Insert into STATUS_COMPLAIN ([NAME])
	values(@p_NAME)
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_update_STATUS_COMPLAIN')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_update_STATUS_COMPLAIN
GO

 CREATE PROCEDURE sp_update_STATUS_COMPLAIN
@p_NAME varchar(250) ,
@w_ID int,
@w_NAME varchar(250) 
AS
BEGIN
	UPDATE [dbo].STATUS_COMPLAIN SET [NAME]=@p_NAME 
	WHERE ID=@w_ID AND NAME=@w_NAME
END 
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_STATUS_ORDER')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_STATUS_ORDER
GO

 CREATE PROCEDURE sp_insert_STATUS_ORDER
@p_NAME varchar(250)  
AS
BEGIN
	Insert into STATUS_ORDER ([NAME])
	values(@p_NAME)
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_update_STATUS_ORDER')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_update_STATUS_ORDER
GO

 CREATE PROCEDURE sp_update_STATUS_ORDER
@p_NAME varchar(250) ,
@w_ID int,
@w_NAME varchar(250) 
AS
BEGIN
	UPDATE [dbo].STATUS_ORDER SET [NAME]=@p_NAME 
	WHERE ID=@w_ID AND NAME=@w_NAME
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_ACCOUNT')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_ACCOUNT
GO

 CREATE PROCEDURE sp_insert_ACCOUNT
@p_USERNAME varchar(100),
@p_PASSWORD varchar(100),
@p_NAME nvarchar(250),
@p_GENDER bit,
@p_EMAIL varchar(250),
@p_PHONE varchar(12),
@p_ADDRESS varchar(250),
@p_ROLE_ID int,
@p_DEPARTMENT_ID int  
AS
BEGIN
	Insert into ACCOUNT (USERNAME,[PASSWORD],[NAME],GENDER,EMAIL,PHONE,ADDRESS,ROLE_ID,DEPARTMENT_ID)
	values(@p_USERNAME,@p_PASSWORD,@p_NAME,@p_GENDER,@p_EMAIL,@p_PHONE,@p_ADDRESS,@p_ROLE_ID,@p_DEPARTMENT_ID)
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_update_ACCOUNT')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_update_ACCOUNT
GO

 CREATE PROCEDURE sp_update_ACCOUNT
@p_USERNAME varchar(100),
@p_PASSWORD varchar(100),
@p_NAME nvarchar(250),
@p_GENDER bit,
@p_EMAIL varchar(250),
@p_PHONE varchar(12),
@p_ADDRESS varchar(250),
@p_ROLE_ID int,
@p_DEPARTMENT_ID int ,
@w_ID int,
@w_USERNAME varchar(100),
@w_PASSWORD varchar(100),
@w_NAME nvarchar(250),
@w_GENDER bit,
@w_EMAIL varchar(250),
@w_PHONE varchar(12),
@w_ADDRESS varchar(250),
@w_ROLE_ID int,
@w_DEPARTMENT_ID int 
AS
BEGIN
	UPDATE [dbo].ACCOUNT SET USERNAME=@p_USERNAME,[PASSWORD]=@p_PASSWORD,[NAME]=@p_NAME,GENDER=@p_GENDER,EMAIL=@p_EMAIL,PHONE=@p_PHONE,ADDRESS=@p_ADDRESS,ROLE_ID=@p_ROLE_ID,DEPARTMENT_ID=@p_DEPARTMENT_ID 
	WHERE ID=@w_ID AND USERNAME=@w_USERNAME AND PASSWORD=@w_PASSWORD AND NAME=@w_NAME AND GENDER=@w_GENDER AND EMAIL=@w_EMAIL AND PHONE=@w_PHONE AND ADDRESS=@w_ADDRESS AND ROLE_ID=@w_ROLE_ID AND DEPARTMENT_ID=@w_DEPARTMENT_ID
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_CLIENT')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_CLIENT
GO

 CREATE PROCEDURE sp_insert_CLIENT
@p_NAME varchar(250),
@p_PHONE varchar(12),
@p_ADDRESS varchar(250),
@p_COMPANY_NAME varchar(250)  
AS
BEGIN
	Insert into CLIENT ([NAME],PHONE,ADDRESS,COMPANY_NAME)
	values(@p_NAME,@p_PHONE,@p_ADDRESS,@p_COMPANY_NAME)
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_update_CLIENT')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_update_CLIENT
GO

 CREATE PROCEDURE sp_update_CLIENT
@p_NAME varchar(250),
@p_PHONE varchar(12),
@p_ADDRESS varchar(250),
@p_COMPANY_NAME varchar(250) ,
@w_ID int,
@w_NAME varchar(250),
@w_PHONE varchar(12),
@w_ADDRESS varchar(250),
@w_COMPANY_NAME varchar(250) 
AS
BEGIN
	UPDATE [dbo].CLIENT SET [NAME]=@p_NAME,PHONE=@p_PHONE,ADDRESS=@p_ADDRESS,COMPANY_NAME=@p_COMPANY_NAME 
	WHERE ID=@w_ID AND NAME=@w_NAME AND PHONE=@w_PHONE AND ADDRESS=@w_ADDRESS AND COMPANY_NAME=@w_COMPANY_NAME
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_PRODUCT_ELEVATION')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_PRODUCT_ELEVATION
GO

 CREATE PROCEDURE sp_insert_PRODUCT_ELEVATION
@p_NAME varchar(250),
@p_TYPE varchar(250),
@p_PRICE decimal,
@p_DATE_OF_ORDER date,
@p_WARRANTY int,
@p_WARRANTY_EXPIRE_DATE date  
AS
BEGIN
	Insert into PRODUCT_ELEVATION ([NAME],[TYPE],PRICE,DATE_OF_ORDER,WARRANTY,WARRANTY_EXPIRE_DATE)
	values(@p_NAME,@p_TYPE,@p_PRICE,@p_DATE_OF_ORDER,@p_WARRANTY,@p_WARRANTY_EXPIRE_DATE)
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_update_PRODUCT_ELEVATION')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_update_PRODUCT_ELEVATION
GO

 CREATE PROCEDURE sp_update_PRODUCT_ELEVATION
@p_NAME varchar(250),
@p_TYPE varchar(250),
@p_PRICE decimal,
@p_DATE_OF_ORDER date,
@p_WARRANTY int,
@p_WARRANTY_EXPIRE_DATE date ,
@w_ID int,
@w_NAME varchar(250),
@w_TYPE varchar(250),
@w_PRICE decimal,
@w_DATE_OF_ORDER date,
@w_WARRANTY int,
@w_WARRANTY_EXPIRE_DATE date 
AS
BEGIN
	UPDATE [dbo].PRODUCT_ELEVATION SET [NAME]=@p_NAME,[TYPE]=@p_TYPE,PRICE=@p_PRICE,DATE_OF_ORDER=@p_DATE_OF_ORDER,WARRANTY=@p_WARRANTY,WARRANTY_EXPIRE_DATE=@p_WARRANTY_EXPIRE_DATE 
	WHERE ID=@w_ID AND NAME=@w_NAME AND TYPE=@w_TYPE AND PRICE=@w_PRICE AND DATE_OF_ORDER=@w_DATE_OF_ORDER AND WARRANTY=@w_WARRANTY AND WARRANTY_EXPIRE_DATE=@w_WARRANTY_EXPIRE_DATE
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_ORDER_DETAIL')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_ORDER_DETAIL
GO

 CREATE PROCEDURE sp_insert_ORDER_DETAIL
@p_ORDERS_ID int,
@p_PRODUCT_ID int,
@p_NUM_OF_SYSTEM_INSTALLED int,
@p_PRICE decimal,
@p_WARRANTY_PERIOD int,
@p_WARRANTY_EXPIRE_DATE date  
AS
BEGIN
	Insert into ORDER_DETAIL (ORDERS_ID,PRODUCT_ID,NUM_OF_SYSTEM_INSTALLED,PRICE,WARRANTY_PERIOD,WARRANTY_EXPIRE_DATE)
	values(@p_ORDERS_ID,@p_PRODUCT_ID,@p_NUM_OF_SYSTEM_INSTALLED,@p_PRICE,@p_WARRANTY_PERIOD,@p_WARRANTY_EXPIRE_DATE)
END
GO



IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_ORDERS')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_ORDERS
GO

 CREATE PROCEDURE sp_insert_ORDERS
@p_CLIENT_ID int,
@p_ACCOUNT_ID int,
@p_TOTAL_PRICE decimal,
@p_DATE_OF_ORDER date,
@p_DATE_OF_SYSTEM_INSTALLED date,
@p_DATE_OF_COMPLETE date,
@p_STATUS_ID int  
AS
BEGIN
	Insert into ORDERS (CLIENT_ID,ACCOUNT_ID,TOTAL_PRICE,DATE_OF_ORDER,DATE_OF_SYSTEM_INSTALLED,DATE_OF_COMPLETE,STATUS_ID)
	values(@p_CLIENT_ID,@p_ACCOUNT_ID,@p_TOTAL_PRICE,@p_DATE_OF_ORDER,@p_DATE_OF_SYSTEM_INSTALLED,@p_DATE_OF_COMPLETE,@p_STATUS_ID)
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_update_ORDERS')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_update_ORDERS
GO

 CREATE PROCEDURE sp_update_ORDERS
@p_STATUS_ID int ,
@w_ID int,
@w_STATUS_ID int 
AS
BEGIN
	UPDATE [dbo].ORDERS SET STATUS_ID=@p_STATUS_ID 
	WHERE ID=@w_ID AND STATUS_ID=@w_STATUS_ID
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_insert_COMPLAIN')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_insert_COMPLAIN
GO

 CREATE PROCEDURE sp_insert_COMPLAIN
@p_ORDER_ID int,
@p_ACCOUNT_ID int,
@p_IS_CHARGEABLE bit,
@p_PROBLEM varchar(250),
@p_DATE_COMPLAIN date,
@p_STATUS_ID int,
@p_TECHNICIAN_PERSON varchar(250)  
AS
BEGIN
	Insert into COMPLAIN (ORDER_ID,ACCOUNT_ID,IS_CHARGEABLE,PROBLEM,DATE_COMPLAIN,STATUS_ID,TECHNICIAN_PERSON)
	values(@p_ORDER_ID,@p_ACCOUNT_ID,@p_IS_CHARGEABLE,@p_PROBLEM,@p_DATE_COMPLAIN,@p_STATUS_ID,@p_TECHNICIAN_PERSON)
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'sp_update_COMPLAIN')AND type in (N'P', N'PC'))
DROP PROCEDURE sp_update_COMPLAIN
GO

 CREATE PROCEDURE sp_update_COMPLAIN
@p_IS_CHARGEABLE bit,
@p_PROBLEM varchar(250),
@p_DATE_COMPLAIN date,
@p_STATUS_ID int,

@w_ID int,
@w_IS_CHARGEABLE bit,
@w_PROBLEM varchar(250),
@w_DATE_COMPLAIN date,
@w_STATUS_ID int

AS
BEGIN
	UPDATE [dbo].COMPLAIN SET IS_CHARGEABLE=@p_IS_CHARGEABLE,PROBLEM=@p_PROBLEM,DATE_COMPLAIN=@p_DATE_COMPLAIN,STATUS_ID=@p_STATUS_ID
	WHERE ID=@w_ID AND  IS_CHARGEABLE=@w_IS_CHARGEABLE AND PROBLEM=@w_PROBLEM AND DATE_COMPLAIN=@w_DATE_COMPLAIN AND STATUS_ID=@w_STATUS_ID
END
GO
